services:
  db:
    image: postgres:14
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - 5432:5432

  k6:
    image: loadimpact/k6:latest
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "6565:6565"
    volumes:
      - ./k6:/k6

  message-broker:
    image: rabbitmq:3-management-alpine
    container_name: message-broker
    ports:
      - 5672:5672   # for sender and consumer connections
      - 15672:15672 # for serve RabbitMQ GUI
    restart: unless-stopped
